# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node CI

on:
  push:
    branches: [ master, development ]
  pull_request:
    branches: [ master, development ]

jobs:
  test_pull_request:
    runs-on: ubuntu-latest

    steps:
      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.3.0
        with:
          mongodb-version: 4
          mongodb-replica-set: stopikowo
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 10
      - name: install
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - name: build:prod
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: build:prod
      - name: set env
        uses: allenevans/set-env@v1.0.0
        with:
          MONGO_CONNECTION: 'mongodb://localhost:27017'
          MONGO_DATABASE: ''
      - name: test
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: test