# # This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# # For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

# name: Node CI

# on:
#   push:
#     branches: [ master, development ]
#   pull_request:
#     branches: [ master, development ]

# jobs:
#   test_pull_request:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Start MongoDB
#         uses: supercharge/mongodb-github-action@1.3.0
#         with:
#           mongodb-version: 4.2
#           mongodb-replica-set: test
#       - uses: actions/checkout@v2
#       - uses: actions/setup-node@v1
#         with:
#           node-version: 10
#       - name: Installing dependencies
#         uses: borales/actions-yarn@v2.0.0
#         with:
#           cmd: install
#       # - name: Bulding Production
#       #   uses: borales/actions-yarn@v2.0.0
#       #   with:
#       #     cmd: build:prod
#       - name: Setting Enviromentals
#         uses: allenevans/set-env@v1.0.0
#         with:
#           MONGO_CONNECTION: 'mongodb://test:27017'
#           MONGO_DATABASE: 'test'
#       - name: Testing
#         uses: borales/actions-yarn@v2.0.0
#         with:
#           cmd: test

on: [push]

jobs:
  test_mongo_action:
    runs-on: ubuntu-latest
    name: Test mongo-action
    steps:
      - name: Create mongo Docker container
        id: build_mongo_docker
        uses: DigiPie/mongo-action@v1.0.0
        with:
          image-version: latest
          port: 27017
      - name: Install mongodb-clients
        id: install_mongodb_clients
        run: sudo apt install mongodb-clients
      - name: Test mongo connection
        id: test_mongo_connection
        run: "sudo mongo localhost:27017"